spring:
  application:
    name: ${APPLICATION_NAME}
  profiles:
    active: ${PROFILES_ACTIVE}
  main:
    log-startup-info: ${LOG_STARTUP_INFO}
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED}
    change-log: classpath:db/changelog/changelog.yaml
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_JDBC}://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      transaction:
        jta:
          platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    show-sql: ${SHOW_SQL}
    open-in-view: ${OPEN_IN_VIEW}

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: ${SHOW_ACTUATOR}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT} # TRACE, DEBUG, INFO, WARN, ERROR, FATAL
  file:
    path: ${LOGGING_FILE_PATH}
    name: ${LOGGING_FILE_NAME}

management:
  endpoints:
    web:
      exposure:
        include: ${INCLUDE}
  endpoint:
    health:
      show-details: ${SHOW_DETAILS}
