apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: spring-boot-template
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM= # postgres (base64)
  POSTGRES_DB: c3ByaW5nLWJvb3QtdGVtcGxhdGU= # spring-boot-template (base64)
