apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-template-config
  namespace: spring-boot-template
data:
  SPRING_APPLICATION_NAME: spring-boot-template
  SPRING_PROFILES_ACTIVE: develop
  LOG_STARTUP_INFO: "false"
  SPRING_LIQUIBASE_ENABLED: "true"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring-boot-template
  SPRING_DATASOURCE_USERNAME: postgres
  HIBERNATE_DDL_AUTO: none
  SHOW_SQL: "false"
  OPEN_IN_VIEW: "false"
  SERVER_PORT: "8080"
  SHOW_ACTUATOR: "true"
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_FILE_PATH: app
  LOGGING_FILE_NAME: app/file.log
  INCLUDE: "*"
  SHOW_DETAILS: always
