INSERT INTO vocabulary (word, phonetic, word_type, word_type_en, meaning_vn, meaning_explanation_vn, verb_forms, example, example_meaning) VALUES  
('afraid', '/əˈfreɪd/', 'Tính từ', 'Adjective', 'Sợ', 'Có cảm giác lo lắng hoặc không an toàn về điều gì đó.', '-', 'I am afraid of the dark.', 'Tôi sợ bóng tối.'),  
('agree', '/əˈɡriː/', 'Động từ', 'Verb', 'Đồng ý', 'Có chung ý kiến hoặc ý tưởng với người khác.', 'agree - agreed - agreed', 'They agree with the plan.', 'Họ đồng ý với kế hoạch.'),  
('angry', '/ˈæŋɡri/', 'Tính từ', 'Adjective', 'Giận dữ', 'Có cảm giác không hài lòng hoặc bực tức về điều gì.', '-', 'She was angry at the delay.', 'Cô ấy đã giận dữ vì sự chậm trễ.'),  
('arrive', '/əˈraɪv/', 'Động từ', 'Verb', 'Đến', 'Đến một địa điểm nào đó sau một khoảng thời gian di chuyển.', 'arrive - arrived - arrived', 'The train will arrive at noon.', 'Tàu sẽ đến vào buổi trưa.'),  
('attack', '/əˈtæk/', 'Động từ', 'Verb', 'Tấn công', 'Hành động xâm hoặc gây hại cho ai đó hoặc cái gì đó.', 'attack - attacked - attacked', 'The dog will attack intruders.', 'Chó sẽ tấn công kẻ xâm nhập.'),  
('bottom', '/ˈbɑːtəm/', 'Danh từ', 'Noun', 'Đáy', 'Phần thấp nhất hoặc cơ sở của vật gì đó.', '-', 'The book is at the bottom of the pile.', 'Quyển sách ở đáy chồng sách.'),  
('clever', '/ˈklɛvər/', 'Tính từ', 'Adjective', 'Thông minh', 'Có khả năng hiểu nhanh hoặc giải quyết vấn đề.', '-', 'He came up with a clever idea.', 'Anh ấy đã đưa ra một ý tưởng thông minh.'),  
('cruel', '/kruːəl/', 'Tính từ', 'Adjective', 'Độc ác', 'Có hành động hoặc sự đối xử tàn nhẫn với người khác.', '-', 'It was a cruel joke.', 'Đó là một trò đùa độc ác.'),  
('finally', '/ˈfaɪnəli/', 'Trạng từ', 'Adverb', 'Cuối cùng', 'Sau một thời gian dài, cuối cùng đã đến.', '-', 'They finally reached their destination.', 'Họ cuối cùng đã đến đích.'),  
('hide', '/haɪd/', 'Động từ', 'Verb', 'Ẩn giấu', 'Giữ ai đó hoặc cái gì đó không thể nhìn thấy hoặc không được biết đến.', 'hide - hid - hidden', 'She likes to hide toys.', 'Cô ấy thích ẩn giấu đồ chơi.'),  
('hunt', '/hʌnt/', 'Động từ', 'Verb', 'Săn', 'Tìm kiếm và bắt hoặc giết động vật hoặc cá.', 'hunt - hunted - hunted', 'They hunt deer in the forest.', 'Họ săn nai trong rừng.'),  
('lot', '/lɑːt/', 'Danh từ', 'Noun', 'Nhiều', 'Một lượng lớn hoặc số lượng lớn của cái gì đó.', '-', 'There are a lot of stars in the sky.', 'Có rất nhiều ngôi sao trên bầu trời.'),  
('middle', '/ˈmɪdəl/', 'Danh từ', 'Noun', 'Giữa', 'Vị trí ở giữa của một cái gì đó.', '-', 'Sit in the middle of the row.', 'Ngồi giữa hàng ghế.'),  
('moment', '/ˈmoʊ.mənt/', 'Danh từ', 'Noun', 'Khoảng khắc', 'Một khoảng thời gian ngắn, có thể rất quan trọng.', '-', 'Enjoy the moment.', 'Tận hưởng khoảnh khắc.'),  
('pleased', '/pliːzd/', 'Tính từ', 'Adjective', 'Hài lòng', 'Có cảm giác vui mừng hoặc thoải mái về điều gì đó.', '-', 'She was pleased with the results.', 'Cô ấy hài lòng với kết quả.'),  
('promise', '/ˈprɑː.mɪs/', 'Động từ/Danh từ', 'Verb/Noun', 'Hứa', 'Cam kết sẽ làm điều gì đó cho người khác.', 'promise - promised - promised', 'He made a promise to help her.', 'Anh ấy đã hứa sẽ giúp cô ấy.'),  
('reply', '/rɪˈplaɪ/', 'Động từ', 'Verb', 'Trả lời', 'Đưa ra câu trả lời cho một câu hỏi hoặc lời nói.', 'reply - replied - replied', 'Please reply to my message.', 'Vui lòng trả lời tin nhắn của tôi.'),  
('safe', '/seɪf/', 'Tính từ', 'Adjective', 'An toàn', 'Không có nguy cơ bị hại hoặc nguy hiểm.', '-', 'The children are safe at home.', 'Trẻ em thì an toàn ở nhà.'),  
('trick', '/trɪk/', 'Danh từ', 'Noun', 'Mẹo', 'Một hành động lừa dối hoặc gây nhầm lẫn cho người khác.', '-', 'It was a clever trick.', 'Đó là một mẹo thông minh.'),  
('well', '/wɛl/', 'Trạng từ', 'Adverb', 'Tốt', 'Ở trạng thái tốt, đem lại kết quả tích cực.', '-', 'She plays the piano well.', 'Cô ấy chơi piano giỏi.');
